### ISSUE TITLE
"Could not parse clipboard as SNBT"

### ISSUE THREAD

**Issue by Vap0r1ze** [RealRTTV/nbtworkbench#11]
I think this is valid SNBT but the web editor is telling me its unable to parse it, it would also be cool if the error told me the index where the parsing failed so I could debug if the input is malformed myself.

Btw sick project!

<pre>
[{Count:1b,Slot:0b,id:"minecraft:diamond_block",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute code when something","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"is done by (or happens to) a player.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Detect when a player joins the plot","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Detect when a player right clicks","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Detect when a player dies","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"aqua","text":"Player Event"}'}}},{Count:1b,Slot:1b,id:"minecraft:oak_planks",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute the code inside it","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"if a certain condition related to a","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"player is met.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a player is swimming","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a player has an item","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check a player\'s username","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"gold","text":"If Player"}'}}},{Count:1b,Slot:2b,id:"minecraft:cobblestone",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to do something related to","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"a player or multiple players.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Send a message to a player","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Damage or heal a player","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Clear a player\'s inventory","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"green","text":"Player Action"}'}}},{Count:1b,Slot:3b,id:"minecraft:lapis_ore",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to call functions declared by","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"a Function block.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"Code will not continue past this block","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"until the Function completes/returns.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"blue","text":"Call Function"}'}}},{Count:1b,Slot:4b,id:"minecraft:emerald_ore",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to start processes declared by","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"a Process block.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"Waits inside the Process will not","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"stop this code line, unlike Functions.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"dark_green","text":"Start Process"}'}}},{Count:1b,Slot:5b,id:"minecraft:ender_eye",tag:{CustomModelData:5000,PublicBukkitValues:{"hypercube:varitem":'{"id":"pn_el","data":{"name":"name","type":"any","plural":false,"optional":false}}'},display:{Lore:['{"italic":false,"extra":[{"color":"#FFD47F","text":"Any Value"},{"color":"dark_gray","text":" - "},{"color":"gray","text":"name"}],"text":""}'],Name:'{"italic":false,"color":"#AAFFAA","text":"name"}'}}},{Count:1b,Slot:6b,id:"minecraft:prismarine_shard",tag:{CustomModelData:5000,PublicBukkitValues:{"hypercube:varitem":'{"id":"vec","data":{"x":0.0,"y":0.0,"z":0.0}}'},display:{Lore:['{"italic":false,"extra":[{"color":"#AAAAAA","text":"X:"}," ",{"color":"#FFFFFF","text":"0.0"}],"text":""}','{"italic":false,"extra":[{"color":"#AAAAAA","text":"Y:"}," ",{"color":"#FFFFFF","text":"0.0"}],"text":""}','{"italic":false,"extra":[{"color":"#AAAAAA","text":"Z:"}," ",{"color":"#FFFFFF","text":"0.0"}],"text":""}'],Name:'{"italic":false,"color":"#2AFFAA","text":"Vector"}'}}},{Count:1b,Slot:8b,id:"minecraft:iron_ingot",tag:{CustomModelData:5050,HideFlags:255,PublicBukkitValues:{"hypercube:item_instance":"6093f966-01d2-4717-b012-c6ccd1a64006"},display:{Lore:['{"text":"","extra":[{"text":"Right click this to obtain values. Types include","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"numbers, variables, text, sound effects, game","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"values, potion effects, and spawn eggs.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"white","text":"Values"}'}}},{Count:1b,Slot:9b,id:"minecraft:coal_block",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to control the execution of","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"some or all code blocks after it.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Pause the code sequence","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"for a certain duration","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Stop the code sequence","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Skip a repeat iteration","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"blue","text":"Control"}'}}},{Count:1b,Slot:10b,id:"minecraft:purpur_block",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to change the selection on the","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"current line of code, which will affect","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"the targets of most code blocks.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Select all players on the plot","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Select a player with a certain username","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Select all players on the plot that meet","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"a certain condition","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"light_purple","text":"Select Object"}'}}},{Count:1b,Slot:11b,id:"minecraft:prismarine",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to repeat the code inside it.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Repeat code forever","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Repeat code a certain number","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"of times","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Repeat code until a certain","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"condition is met","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"green","text":"Repeat"}'}}},{Count:1b,Slot:12b,id:"minecraft:end_stone",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute the code inside it","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"if the condition directly before it","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"was not met. Else must be placed directly","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"after any If block\'s closing bracket.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"dark_aqua","text":"Else"}'}}},{Count:1b,Slot:17b,id:"minecraft:written_book",tag:{CustomModelData:0,HideFlags:255,PublicBukkitValues:{"hypercube:item_instance":"be1198ac-f1a9-4db1-a246-1782550ef11f"},display:{Lore:['{"text":"","extra":[{"text":"Right-click to open the","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"reference menu.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"extra":[{"color":"gold","text":"◆ "},{"color":"aqua","text":"Reference Book "},{"color":"gold","text":"◆"}],"text":""}'}}},{Count:1b,Slot:18b,id:"minecraft:iron_block",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to set the value of a variable.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Set a variable to a sum of numbers","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Remove all instances of a certain","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"string from a string variable","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Set a variable to a random value","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"yellow","text":"Set Variable"}'}}},{Count:1b,Slot:19b,id:"minecraft:obsidian",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute the code inside it","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"if a certain condition related to the","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"value of a variable is met.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a number variable is less","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"than or equal to another number","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a string variable contains","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"a certain string","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a variable is equal","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"to something","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"gold","text":"If Variable"}'}}},{Count:1b,Slot:20b,id:"minecraft:netherrack",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to do something related to","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"the plot and everyone playing it.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Spawn a mob or other entity","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Change a block or block region","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"red","text":"Game Action"}'}}},{Count:1b,Slot:21b,id:"minecraft:red_nether_bricks",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute the code inside","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"it if a certain condition related","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"to the plot is met.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a container has all of","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"a certain set of items","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a sign\'s text contains","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"a certain text","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if a block at a certain","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"location is a certain block","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"red","text":"If Game"}'}}},{Count:1b,Slot:26b,id:"minecraft:blaze_rod",tag:{CustomModelData:0,HideFlags:255,PublicBukkitValues:{"hypercube:item_instance":"6a04920b-82d1-45b9-b459-071d638868c3"},display:{Lore:['{"text":"","extra":[{"text":"Shows two corresponding brackets","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"for a short amount of time.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"Right-Click a bracket to highlight","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"both.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"gold","text":"Bracket Finder"}'}}},{Count:1b,Slot:27b,id:"minecraft:gold_block",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute code when an entity","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"does something or when something","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"happens to an entity.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Detect when a mob takes damage","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Detect when a projectile kills a mob","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Detect when a mob kills another mob","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"yellow","text":"Entity Event"}'}}},{Count:1b,Slot:28b,id:"minecraft:bricks",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute the code inside it","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"if a certain condition related to an","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"entity or multiple entities is met.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if an entity is a projectile","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check if an entity is a certain type","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"of mob","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Check the name of an entity","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"dark_green","text":"If Entity"}'}}},{Count:1b,Slot:29b,id:"minecraft:mossy_cobblestone",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to do something related to","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"an entity or multiple entities.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Example:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Set the age or size of a mob","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Give a mob a potion effect","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","italic":false,"color":"aqua"},{"text":"Delete an entity from the plot","italic":false,"color":"gray"}]}'],Name:'{"italic":false,"color":"red","text":"Entity Action"}'}}},{Count:1b,Slot:30b,id:"minecraft:lapis_block",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to define a line of code that can be","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"called with a Call Function block.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Additional Info:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"blue","bold":false}]}','{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"aqua","bold":false},{"text":"Set the function name by right clicking","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"the code block sign with a ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false},{"text":"string","italic":false,"color":"aqua"},{"text":".","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"aqua","bold":false},{"text":"Set the name color, icon, and lore of the","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"function by putting an item in the chest.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"aqua","bold":false},{"text":"Put ","italic":false,"color":"gray"},{"text":"parameter","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"#AAFFAA","bold":false},{"text":" items to specify the","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"parameters of the function.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"aqua","bold":false},{"text":"Functions can also be used for continuing","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"lines of code that are out of space.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"aqua","text":"Function"}'}}},{Count:1b,Slot:31b,id:"minecraft:emerald_block",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Used to execute code when the process","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"is started using a Start Process block.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','""','{"text":"","extra":[{"text":"Additional Info:","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"blue","bold":false}]}','{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"aqua","bold":false},{"text":"Set the process name by right clicking","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"the code block sign with a ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false},{"text":"string","italic":false,"color":"aqua"},{"text":".","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"aqua","bold":false},{"text":"Set the name color, icon, and lore of the","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"process by putting an item in the chest.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"» ","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"aqua","bold":false},{"text":"Processes are not a replacement for","italic":false,"color":"gray"}]}','{"text":"","extra":[{"text":"Functions. Processes are much more CPU","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"intensive than functions, and should only","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"be used when needed.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"green","text":"Process"}'}}},{Count:1b,Slot:35b,id:"minecraft:spectral_arrow",tag:{CustomModelData:0,HideFlags:255,display:{Lore:['{"text":"","extra":[{"text":"Click on a Condition block with this","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}','{"text":"","extra":[{"text":"to switch between \'IF\' and \'IF NOT\'.","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"gray","bold":false}]}'],Name:'{"italic":false,"color":"#FFD47F","text":"NOT Arrow"}'}}}]
</pre>

**Comment by RealRTTV** [comment]
it failing was not your fault, it had a crlf at the end, fixed it in 1.3.5

**Comment by Vap0r1ze** [comment]
This issue still persists for me, now saying `(failed at index 0)`. Inspecting my paste by logging `navigator.clipboard.readText()` says there's no leading/trailing whitespace.
If it helps, I'm on latest Chrome on Windows 10

**Comment by RealRTTV** [comment]
chrome paste might not work yet because they are annoying bitches, is is still present today in the newest release?
