### ISSUE TITLE
Feature Suggestion - "Paste from Clipboard" option in right click wheel

### ISSUE THREAD

**Issue by thecolonel63** [RealRTTV/nbtworkbench#12]
You can copy the SNBT to the clipboard from the right click wheel, but the only way to paste is via the drop-in approach, either via the keyboard hotkey 'v' or via the "Clipboard" option in the menu bar.

Adding in the ability to paste via the right click wheel could be a nice companion to the copy to clipboard ability.

**Comment by RealRTTV** [comment]
I like the idea, but would pasting via the right-click menu work? the entries in the right-click menu are based on the type present, with types like compounds having their special actions and types like `ints` having their actions, if we were to add the paste action, what would it do, add to the compound directly or change the held entry to be of the clipboard?

**Comment by thecolonel63** [comment]
I was imagining it would be an option exclusive to compound tags that lets you paste an element at the top, or perhaps it would just check to make sure the clipboard entry is valid before attempting to insert the element where right clicked

**Comment by RealRTTV** [comment]
id love that feature except websites require a ctrl v directly for every clipboard interaction (I still haven't gotten around to doing that yet)

I could make it apply to all complex types and try to parse and see if it can be inserted but the "only appears while clipboard" would be difficult, and also create problems for people to discover the features existence itself

**Comment by RealRTTV** [comment]
(reopening since i haven't added it yet and should have a reminder)

**Comment by RealRTTV** [comment]
added in recent commit
