### ISSUE TITLE
Tiny UI on 4k display

### ISSUE THREAD

**Issue by QuinStudios** [RealRTTV/nbtworkbench#13]
This isn't a technical issue, since the program technically works, but on a 4k monitor, the UI is insanely small and it's really hard to see anything. And since there aren't UI scaling options, there's really nothing that can be done about that.

**Comment by RealRTTV** [comment]
Does Ctrl + or Ctrl - work?

**Comment by QuinStudios** [comment]
No, nor does Ctrl scrolling. It says "Scale: 1x (Max 1)"

**Comment by RealRTTV** [comment]
You can always put them here under Issues.

Does it still max out at 1x when it's full-screened?

**Comment by QuinStudios** [comment]
Ah, good idea. No, UI scaling does work when it's full-screened

**Comment by QuinStudios** [comment]
Okay, I see now that this has been brought up in a resolved issue, and I can confirm that if I make the window bigger, even not full screen, it does allow me to change the UI scale. So, technically, feel free to resolve this issue now.

However, I will add that it could definitely be improved. Whether that be changing the default window size to be a bit bigger to allow some UI scaling, adding intermediary UI scaling steps so it's more granular, adding some kind of settings option or something for changing scale, etc.

Perhaps the most logical choice would be to make the tool remember your window size and UI scaling. I assume this is possible, considering it can remember your theme selection. Also, at the very least, maybe you should update the description with a quick disclaimer that you may need to increase your window size for UI scaling to work.

**Comment by RealRTTV** [comment]
I'll make the window size a % of your screen's size, and to cache it in config, along with your current scale size. Currently it should be incrementing in +0.5x per each, thanks. I'll close when committed
