### ISSUE TITLE
Search Results Not Cleared With Successive Searches

### ISSUE THREAD

**Issue by QuinStudios** [RealRTTV/nbtworkbench#15]
If you run a text search, and then run another one, the results of both searches stay permanently visible, at least as far as I can tell. This means that if you accidentally, say, run a search of "e", it becomes impossible to get useful search results without closing out of the application, re-opening the file, and re-doing the search.

**Comment by RealRTTV** [comment]
yeah that's intentional, you can hold shift and click the button or do a shift + enter to clear all bookmarks, I wanted a simple way to do "or" on searches, although if you think it would be better to clear all bookmarks before a search, I could do that.

**Comment by QuinStudios** [comment]
I think the "or" functionality is useful, but probably less commonly desired. So maybe just flipping the functionality would make the most sense. So, Shift + Enter for a search would compound the results like it currently does, but by default the search would just clear.
