### ISSUE TITLE
Spam click open file opens a bunch of dialogs

### ISSUE THREAD

**Issue by tryashtar** [RealRTTV/nbtworkbench#3]
There's a bit of a delay when you click the open file button. If you click it multiple times before the open file dialog pops up, then after closing the dialog, another one will appear, and so on.

In fact, even when the file dialog is open and the app looks unresponsive, you can still click the button repeatedly and queue up more popups.

**Comment by RealRTTV** [comment]
yeah winit is holding back on the events while the window is open, after they come through, the window seems to send all these requests

atm I think the best course of action is adding a nullify time, where once the window closes, I set a nullify time to be 500ms in the future, so all packets that come from now til then are discarded

not sure if this is a satisfactory solution tho

**Comment by RealRTTV** [comment]
ok i made it ignore for 50ms, should be fixed
