### ISSUE TITLE
Responsiveness: mouse up interacts with most things

### ISSUE THREAD

**Issue by tryashtar** [RealRTTV/nbtworkbench#5]
Most buttons in this program are activated or selected when the mouse is released. This makes it feel less responsive, and can cause problems like when you click on something, then move the mouse a bit, then release, it will use the wrong thing.

**Comment by RealRTTV** [comment]
can you list some that you feel are appropriate to be on press?

**Comment by tryashtar** [comment]
* selecting a tag
* saving/closing tab
* new/open file
* everything on the toolbar basically
* expanding/collapsing a nested tag
