### ISSUE TITLE
Crash when clicking tag then anywhere

### ISSUE THREAD

**Issue by tryashtar** [RealRTTV/nbtworkbench#6]
I haven't yet figured out how to add tags to the tree, because when I click a tag on the toolbar, it adds it to my mouse, then when I click anywhere else, it crashes with this output:
```
thread 'main' panicked at library/core/src/panicking.rs:219:5:
unsafe precondition(s) violated: hint::unreachable_unchecked must never be reached
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
```

**Comment by RealRTTV** [comment]
**i am an idiot sometimes**

**Comment by RealRTTV** [comment]
try it with a non-primitive tag and it'll work, I know what I did wrong

**Comment by RealRTTV** [comment]
god that's stupid of me
