### ISSUE TITLE
Question: scale and theme

### ISSUE THREAD

**Issue by tryashtar** [RealRTTV/nbtworkbench#8]
Is there a way to change the scale and theme? It's a bit small for me, and I find the dark color of the background difficult to see.

**Comment by RealRTTV** [comment]
scale is ctrl and + / -

**Comment by tryashtar** [comment]
It doesn't seem to work for me, I tried left and right ctrl with top and numpad +/-

**Comment by RealRTTV** [comment]
it works on mine, are you on the web or exe?

**Comment by tryashtar** [comment]
I'm just using a locally built version. It does seem to work at least to some extent on the web one

**Comment by RealRTTV** [comment]
if your window is too small, it won't be able to scale up since the toolbar would be cutoff

**Comment by RealRTTV** [comment]
accidently wrote #2 instead of #8 whoopsies
