### ISSUE TITLE
Crash when editing wrong type into list

### ISSUE THREAD

**Issue by tryashtar** [RealRTTV/nbtworkbench#9]
Take a list, then right-click it and go into external text editor SNBT mode. Like a list of longs for example. Change one of them to be the wrong type, like a float, then save. The program crashes with this output:
```
thread 'main' panicked at library/core/src/panicking.rs:219:5:
unsafe precondition(s) violated: hint::unreachable_unchecked must never be reached
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
```

**Comment by RealRTTV** [comment]
why didnt i handle this
